version: '3.1'

services:

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db/db_data:/var/lib/postgresql/data

  migration:
    image: api
    command: bash -c "python manage.py makemigrations cur_transfers && python manage.py migrate"
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  test_api:
    image: api
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/currency_transfers
    ports:
      - 8000:8000
    depends_on:
      - db
